version: '3'
services:
  owo-mysql:
    container_name: owo-db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - owomysql:/var/lib/mysql
    ports:
      - 9100:3306

  owo-redis:
    container_name: owo-redis
    image: redis:6.2.6-alpine
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    restart: unless-stopped
    ports:
      - 9101:6379

  frontend:
    container_name: owo-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 9000:80
    volumes:
      - ./frontend:/app
      - ./docker.env:/app/.env

  backend-node:
    container_name: owo-backend-node
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    ports:
      - 9002:8000
    volumes:
      - ./docker.env:/app/.env
      - ./frontend/public:/frontend/public
      - ./backend-node:/app
      - ./tests:/tests
    depends_on:
      - owo-mysql
      - owo-redis

  backend-go:
    container_name: owo-backend-go
    platform: linux/amd64
    build:
      context: ./backend-go/dev
      dockerfile: Dockerfile
    ports:
      - 9001:8000
    volumes:
      - ./backend-go:/app
      - ./docker.env:/app/.env
      - ./frontend/public:/frontend/public
      - ./tests:/tests
      - gomod:/go/pkg/mod
      - gocache:/root/.cache/go-build
    command: [ "air", "-c", "./dev/.air.conf" ]
    restart: unless-stopped
    depends_on:
      - owo-mysql
      - owo-redis

  backend-go-sse:
    container_name: owo-backend-go-sse
    platform: linux/amd64
    build:
      context: ./backend-go-sse/dev
      dockerfile: Dockerfile
    ports:
      - 9003:8000
    volumes:
      - ./backend-go-sse:/app
      - ./docker.env:/app/.env
      - gomodSSE:/go/pkg/mod
      - gocacheSSE:/root/.cache/go-build
    command: [ "air", "-c", "./dev/.air.conf" ]
    restart: unless-stopped
    depends_on:
      - owo-redis
  # prod-backend-go:
  #   container_name: prod-backend-go
  #   platform: linux/amd64
  #   build:
  #     context: ./backend-go
  #     dockerfile: Dockerfile
  #   ports:
  #     - 9001:8000
  #   volumes:
  #     - ./backend-go:/app
  #     - gomodProd:/go/pkg/mod
  #     - gocacheProd:/root/.cache/go-build
  #   restart: unless-stopped
  #   depends_on:
  #     - mysql
volumes:
  gomod:
  gocache:
  owomysql:
  gomodSSE:
  gocacheSSE:
