version: '3'
services:
  owo-redis:
    container_name: owo-redis
    image: redis:6.2.6-alpine
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - oworedis:/data
    restart: unless-stopped
    ports:
      - 9101:6379

  owo-mysql:
    container_name: owo-db
    image: mysql:8.0
    restart: unless-stopped
    command: --max_connections=200
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - owomysql:/var/lib/mysql
      - ./mysqld-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 9102:3306

  frontend:
    container_name: owo-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 9000:80
    volumes:
      - ./frontend:/app
      - ./docker.env:/app/.env

  backend-node:
    container_name: owo-backend-node
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    ports:
      - 9002:8000
    volumes:
      - ./docker.env:/app/.env
      - ./frontend/public:/frontend/public
      - ./backend-node:/app
      - ./tests:/tests
    depends_on:
      - owo-mysql
      - owo-redis

  backend-go:
    container_name: owo-backend-go
    platform: linux/amd64
    build:
      context: ./backend-go
      # context: ./backend-go/dev
      dockerfile: Dockerfile
    ports:
      - 9001:8000
    volumes:
      - ./backend-go:/app
      - ./docker.env:/app/.env
      - ./frontend/public:/frontend/public
      - ./tests:/tests
      - owogomod:/go/pkg/mod
      - owogocache:/root/.cache/go-build
    # command: [ "air", "-c", "./dev/.air.conf" ]
    deploy:
      resources:
        limits:
          cpus: '0.6'
    restart: unless-stopped
    depends_on:
      - owo-mysql
      - owo-redis

  backend-go-sse:
    container_name: owo-backend-go-sse
    platform: linux/amd64
    build:
      context: ./backend-go-sse
      # context: ./backend-go-sse/dev
      dockerfile: Dockerfile
    ports:
      - 9003:8000
    volumes:
      - ./backend-go-sse:/app
      - ./docker.env:/app/.env
      - owogomodSSE:/go/pkg/mod
      - owogocacheSSE:/root/.cache/go-build
    # command: [ "air", "-c", "./dev/.air.conf" ]
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '512M'
    restart: unless-stopped
    depends_on:
      - owo-redis

volumes:
  owogomod:
  owogocache:
  owomysql:
  oworedis:
  owogomodSSE:
  owogocacheSSE:
