
CREATE TABLE `go_tbl_faspay_reports` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `upload_logs_id` int(11) DEFAULT NULL,
  `source_id` int(11) DEFAULT '3',
  `channel_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `transaction_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bill_date` datetime DEFAULT NULL,
  `payment_date` datetime DEFAULT NULL,
  `total_bill` decimal(25,2) DEFAULT NULL,
  `total_payment` decimal(25,2) DEFAULT NULL,
  `settlement_service_rate` decimal(5,2) DEFAULT NULL,
  `settlement_service_fee` decimal(25,2) DEFAULT NULL,
  `fee_channel` decimal(25,2) DEFAULT NULL,
  `reconciliation_date` datetime DEFAULT NULL,
  `settlement_date` datetime DEFAULT NULL,
  `total_settlement` decimal(25,2) DEFAULT NULL,
  `bill_number` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bill_reff` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customer_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `matching_id` int(11) DEFAULT NULL,
  `matching_table_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `matching_type_id` int(11) DEFAULT NULL,
  `note` mediumtext COLLATE utf8mb4_unicode_ci,
  `operator_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tbl_faspay_reports_matching_id` (`matching_id`),
  KEY `tbl_faspay_reports_transaction_id` (`transaction_id`),
  KEY `tbl_faspay_reports_payment_date` (`payment_date`),
  KEY `tbl_faspay_reports_total_payment` (`total_payment`),
  KEY `IDX_matching_id_payment_date` (`matching_id`,`payment_date`),
  KEY `IDX_bill_number` (`bill_number`),
  KEY `IDX_bill_reff` (`bill_reff`),
  KEY `idx_tbl_faspay_reports_upload_logs_id` (`upload_logs_id`)
) ENGINE=InnoDB AUTO_INCREMENT=816216 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `node_tbl_faspay_reports` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `upload_logs_id` int(11) DEFAULT NULL,
  `source_id` int(11) DEFAULT '3',
  `channel_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `transaction_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bill_date` datetime DEFAULT NULL,
  `payment_date` datetime DEFAULT NULL,
  `total_bill` decimal(25,2) DEFAULT NULL,
  `total_payment` decimal(25,2) DEFAULT NULL,
  `settlement_service_rate` decimal(5,2) DEFAULT NULL,
  `settlement_service_fee` decimal(25,2) DEFAULT NULL,
  `fee_channel` decimal(25,2) DEFAULT NULL,
  `reconciliation_date` datetime DEFAULT NULL,
  `settlement_date` datetime DEFAULT NULL,
  `total_settlement` decimal(25,2) DEFAULT NULL,
  `bill_number` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bill_reff` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customer_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `matching_id` int(11) DEFAULT NULL,
  `matching_table_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `matching_type_id` int(11) DEFAULT NULL,
  `note` mediumtext COLLATE utf8mb4_unicode_ci,
  `operator_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tbl_faspay_reports_matching_id` (`matching_id`),
  KEY `tbl_faspay_reports_transaction_id` (`transaction_id`),
  KEY `tbl_faspay_reports_payment_date` (`payment_date`),
  KEY `tbl_faspay_reports_total_payment` (`total_payment`),
  KEY `IDX_matching_id_payment_date` (`matching_id`,`payment_date`),
  KEY `IDX_bill_number` (`bill_number`),
  KEY `IDX_bill_reff` (`bill_reff`),
  KEY `idx_tbl_faspay_reports_upload_logs_id` (`upload_logs_id`)
) ENGINE=InnoDB AUTO_INCREMENT=816216 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
